# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbcebc37267c3be403bee3c86aba983d417977c0dae99d6b9555e06d099cfa66be951446df4d77e2e4e62544ff6bcbd4135bcb6c7a37b1989c5a8b50cf9bd467

test:
  secret_key_base: 54d8d2ae082eec36e135038d387dfe3a7134332aef756e66aafe4ebf1a1a2ada960f4b8e23d24c986ada48bebade5061e9481296f57630fc75e3f796eefa6000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
